config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items
  root 'home#index'
  get 'home/about'
  get 'home/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    # belongs_to :user

    BRAND = %w{ Other Nike Addidas TommyHilfiger Puma Zara }
    CONDITION = %w{ Other New Used}
    SIZE = %w{Other Small Meduim Large Xlarge}
    COLOR = %w{Other Black White Green Red Blue Pink Orange Yellow Purple}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @header = "About Us"
  end

  def contact
    @header = "Contact"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
    @header = "Show Cart"
  end

  # GET /items/1 or /items/1.json
  def show
    @header = "Show Cart"
  end

  # GET /items/new
  def new
    @item = Item.new
    @header = "Add Item"
  end

  # GET /items/1/edit
  def edit
    @header = "Edit Item"
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :size, :color, :brand, :condition, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/_footer.html.erb
<section id="home-footer">
    <footer id="main-footer">
        <div class="footer-container">
            <div class="linkedin">
                <a href="https://www.linkedin.com/in/chinonso-john-nkpolukwu-521201138/"><i class="fab fa-linkedin-in fa-2x"></i></a>
            </div>
            <div class="instagram">
                <a href="https://www.instagram.com/johnnsonkp/"><i class="fab fa-instagram fa-2x"></i></a>
            </div>
            <div class="codepen">
                <a href="https://codepen.io/Johnnsonkp"><i class="fab fa-codepen fa-2x"></i></a>
            </div>
            <div class="github">
                <a href="https://github.com/Johnnsonkp"><i class="fab fa-github fa-2x"></i></a>
            </div>
        </div>
        <h5><span class="highlight">Johnnsonkp</span> &copy2021 </h5>
    </footer>

</section>

app/views/home/_header.html.erb
<section id="home-header">
    <nav id="nav-header">
        <div class="container">
            <div class="left">
                <%= link_to "Items.", root_path, class:"navbar-brand" %>
            </div>
            <div class="right">
                <ul class="right-nav">
                    <li>
                        <%= link_to "About Us", home_about_path, class:"nav-link"%>
                    </li>
                    <li>
                        <%= link_to "Contact", home_contact_path, class:"nav-link"%>
                    </li>
                    
                    <% if user_signed_in? %>
                        <li>
                            <%= link_to "Show Cart", items_path, class:"nav-link"%>
                        </li>
                        <li>
                            <%= link_to "Add to Cart", new_item_path, class:"nav-link"%>
                        </li>
                        <li>
                            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
                        </li>
                        <li>
                            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>

                        </li>
                        
                    <% else %>
                        <li>
                            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
                        </li>
                        <li>
                            <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
                        </li>
                    <% end %>
                    
                
                </ul>
            </div>
        </div>
    </nav>
<section>

app/views/home/about.html.erb
<section id="home-about">

    <%= render 'items/showcase' %>
    <%# <h1>About Us</h1> %>
    <div class="wrapper">
        <div class="text">
            <p>Fashion is one of the most critical industries in our world today. Style has become one of the primary ways in which people express their personality and in which they distinguish themselves from those around them. With every New Year which comes and goes new fashions arrive on the scene and they all endeavor to be more colorful and fashionable than those which saw last year. From online retailers like Roden Gray to printed magazines, there’s inspiration everywhere. The desire to express one is something which was present all through human history.

            <p>People of all ages are addicted to new trends in the world of fashion. There is a tremendous amount of competition within the industry and also among consumers. The style is also different among different cultures and nationalities, and this is why it’s so exciting when one travels to various parts of the planet to observe firsthand how people dress in those countries. The clothes we wear has become more than merely a way to cover our nakedness instead it has also become one of the primary ways in which people express themselves.</p>

            <p>Garments which may fit one person may not necessarily be equally suitable for someone else. And even should those clothes be fantastic designer’s efforts, it does not mean that everyone would be equally comfortable when wearing those clothes. Different people will need different styles and designs, something which will be an expression of their uniqueness and personality before they will not be comfortable in wearing that specific fashion design. Human beings are complicated creatures; every one of them has different desires, dreams, and objectives which they deem to be essential to reach a certain level of success in their life. Fashion trends are a critical aspect of that success...<a href="https://www.thefashionisto.com/content/essay-fashion-important/">Read More</a></p>
        </div>
        <div class="right-img">
            <%# <img src="https://images.unsplash.com/photo-1587141121200-3cdb4c1b78a7?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80"> %>
            <%# <img src="https://images.unsplash.com/photo-1567777833528-425b0bf6a99a?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=973&q=80"> %>
            <%# <img src="https://images.unsplash.com/photo-1559697242-7c922c6198c6?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=668&q=80"> %>
            <img src="https://images.unsplash.com/photo-1549777254-896c6739f4dd?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=698&q=80">
        </div>
    </div>
</section>

app/views/home/contact.html.erb
<section id="home-contact">
    <%= render 'items/showcase' %>


</section>

app/views/home/index.html.erb
<section id="home-index">
    <%# <div class="container"> %>
        <div class="showcase"></div>
        <div class="transparent"></div>
        <div class="text">
            <h1>Welcome to Items! </h1>
            <%# <p>An app for organising, prioritising and storing all your online shopping<br> in the one place.</p> %>
            <p>A wishlist shopping cart application designed to organise, prioritize, and store all your<br> online shopping items.</p>
        
            <div class="btns">
                <button class="sign-in"> <i class="fas fa-chevron-left"></i>
                    <% if user_signed_in? %>   
                        <%= link_to "Show Cart", items_path %>
                    <% else %>
                        <%= link_to " Lets Get Started!", new_user_registration_path %>
                    <% end %>
                </button>
            </div>
        </div>
    <%# </div> %>

</section>

app/views/items/_form.html.erb
<section id="items-forms">
  <%= simple_form_for @item, html:{ multipart: true } do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs control">

      <span class="inline">
        <div class='title'>
          <%= f.input :title, required: true, input_html: { class: "input"}, wrapper: false, label_html: {class:"label"} %>
        </div>

        <div class='price control'>
          <%= f.input :price, required: true, input_html: { class: "input", maxlength: 7 }, wrapper: false, label_html: { class:"label"}%>
        </div>
      </span>

      <div class='url'>
          <%= f.input :url, required: true, input_html: { class: "input"}, wrapper: false, label_html: {class:"label"} %>
      </div>

      <div class='description control'>
        <%= f.input :description, required: true, input_html: {class:"textarea"}, wrapper: false, label_html: {class:"label"}%>
      </div>

      <span class="drop-downs">
        <div class='size control'>
          <label class="label">Size</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :size, collection: Item::SIZE, prompt: "Select Size"%>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-tag"></i>
            </span>
          </div>
        </div>

        <div class='color control'>
          <label class="label">Color</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :color, collection: Item::COLOR, prompt: "Select Color"%>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-tag"></i>
            </span>
          </div>
        </div>

        <div class='brand control'>
          <label class="label">Brand</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :brand, collection: Item::BRAND, prompt: "Select Brand"%>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-tag"></i>
            </span>
          </div>
        </div>


        <div class='condition control'>
          <label class="label">Condition</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :brand, collection: Item::CONDITION, prompt: "Select condition"%>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-tag"></i>
            </span>
          </div>
        </div>        

        <%# <%= form_with(model: item) do |form| %> 
          <%# <div class='field form-group'>
              <%= form.number_field :user_id, id: :item_user_id, class:"form-control", value: current_user.id, type: :hidden %>
          <%# </div> %>
        <%# <% end %> 

      </span>
      <div class="hr-container">
        <hr>
      </div>

      <div class="field is-grouped">
        <div class="control">
        <%# <hr> %>
          <%= f.button :submit, class: 'button is-warning' %>
          <%= link_to 'Cancel', items_path, class:'button is-light' %>
        </div>
      </div>

  <% end %>
</section>

app/views/items/_showcase.html.erb
<section id="items-showcase">
    <div class="showcase">
        <%# <%header = " "%> 
        <h1><%= @header %></h1>
    </div>
</section>

app/views/items/edit.html.erb
<%= render 'showcase'%>

<div class="container">
    <%= render 'form', item: @item %>

    <%= link_to 'Show', @item %> |
    <%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<section id="items-index">
  
  <%= render 'showcase' %>
  
  <div class="container">

    <p id="notice"><%= notice %></p>


      <div class="div-container">
        <%# <h1>Shopping Cart</h1> %>
      </div>
    
    <div class="table-content">
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Price</th>
            <%# <th>Description</th> %>
            <th>Size</th>
            <th>Color</th>
            <th>Brand</th>
            <%# <th>Condition</th> %>
            <th>Url</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.title %></td>
              <td><%= item.price %></td>
              <td><%= item.size %></td>
              <td><%= item.color %></td>
              <td><%= item.brand %></td>
              <%#<td><%= item.condition %>
              <td><%= item.url %></td>
              <td><%= link_to 'Show', item %></td>
              <td><%= link_to 'Edit', edit_item_path(item) %></td>
              <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
    </div>

    <br>

    <%= link_to 'New Item', new_item_path, class:'btn' %>
  </div>
</section>

app/views/items/new.html.erb
<section id="new-item">
    <%= render 'showcase' %>
    <div class="container">
            <%# <h1>Add New Item</h1> %>

        <%= render 'form', item: @item %>

        <%# <%= link_to 'Back', items_path, class:"back-btn" %> 
    </div>
</section>

app/views/items/show.html.erb
<div id="showpage">
<p id="notice"><%= notice %></p>
  <div class="container">
    <div class="border">

      <div class="img"></div>

      <div class="content">
        <h1><strong><%= @item.title.capitalize %></strong></h1>

        <div class="properties">
          <p>
            <strong>Brand:</strong>
              <%= @item.brand %>
          </p>

          <p>
            <strong>Color:</strong>
            <%= @item.color %>
          </p>

          <p><strong>Size:</strong>
            <%= @item.size %>
          </p>

          <p><strong>Condition:</strong>
            <%= @item.condition %>
          </p>
        </div>

        <p class="price"><strong>Price:</strong>
          <%= @item.price %>
        </p>

        <div class="description">
          <p>
            <strong>Description:</strong>
            <%= @item.description %>
          </p>
          <p>
            <strong>Url:</strong>
            <%= @item.url %>
          </p>
        </div>
    
        <div class="div-btns">
          <%= link_to 'Edit', edit_item_path(@item), class:"btn" %> 
          <%= link_to 'Back', items_path, class:"btn" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ItemsV3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# External styler sheets %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />

    <%# Google fonts %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Exo+2&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans&family=Exo+2&display=swap" rel="stylesheet">
    
  </head>

  <body>
    <%= render 'home/header'%>
    <%= yield %>
    <%= render 'home/footer'%>
  </body>
</html>